Rswag::Ui.configure do |c|
  # This is the URL generated by grape-swagger and our configuration file app/api/v1/api_grape.rb
  c.swagger_endpoint "/api/v1/swagger_doc.json", "Anime Quiz V1 Docs"

  # Add Basic Auth in case your API is private
  # c.basic_auth_enabled = true
  # c.basic_auth_credentials 'username', 'password'
end
